name: Azure Apps CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'app/frontend/**'
      - '.github/workflows/azure-static-web-apps-frontend.yml'

  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

# Set up permissions for deploying with secretless Azure federated credentials
# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    #container:
      # image: mcr.microsoft.com/azure-dev-cli-apps:latest
      # image: mcr.microsoft.com/azure-cli:latest
    name: Build and Deploy Job
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_FUNCTION_APP: 'func-vrg4tkrp6r3vi-functions'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      # - name: Build And Deploy
      #   id: builddeploy
      #   uses: Azure/static-web-apps-deploy@v1
      #   with:
      #     azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_GLACIER_0F8DBBD0F }}
      #     repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
      #     action: "upload"
      #     ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
      #     # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      #     app_location: "/app/frontend" # App source code path
      #     api_location: "" # Api source code path - optional, manage this seperately by Azure fuunctions
      #     output_location: "dist" # Built app content directory - optional
      #     app_build_command: "npm run build"
      #     ###### End of Repository/Build Configurations ######
      - name: Azure Login
        uses: Azure/login@v2.1.0
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
            
      - name: Install Azure Function Core Tools
        uses: Azure/cli@v2.0.0
        with:
          # Specify the script here
          inlineScript: |
            wget -q https://github.com/Azure/azure-functions-core-tools/releases/download/4.0.5907/Azure.Functions.Cli.linux-x64_net8.4.0.5907.zip
            unzip -d azure-functions-cli Azure.Functions.Cli.linux-x64_net8.4.0.5907.zip
            cd azure-functions-cli
            chmod +x func
            chmod +x gozip
            export PATH=`pwd`:$PATH
            ls
            cd /home/runner/work/AzureFunctionsOpenAI-RAG-Assistant/AzureFunctionsOpenAI-RAG-Assistant/app/backend
            func azure functionapp publish $Env:AZURE_FUNCTION_APP --dotnet-isolated

      # - name: Deploy Function App
      #   uses: Azure/cli@v2.0.0
      #   with:
      #     # Specify the script here
      #     inlineScript: |
      #       cd /home/runner/work/AzureFunctionsOpenAI-RAG-Assistant/AzureFunctionsOpenAI-RAG-Assistant/app/backend
      #       func azure functionapp publish $Env:AZURE_FUNCTION_APP --dotnet-isolated
  
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_GLACIER_0F8DBBD0F }}
          action: "close"
